[package]
name = "canistergeek"
version = "0.0.1"
description = "Canistergeek is the open-source tool for Internet Computer to track your project canisters cycles and memory status and collect log messages."
repository = "https://github.com/fermartz/canistergeek-motoko"